### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by dlevenstein**
Updates so EventTrees code can work with [spiketimes cellNum] style input.

Also some documentation improvements

### CODE REVIEW

**Comment by DavidTingley** [comment]
Ah man I wish I knew you were doing this, I have a spikes2sorted.m function that does a bit of this. Thanks!

**Comment by dlevenstein** [comment]
did it yesterday - I’m using event trees for my project for alex’s modeling class…. some (mildly) interesting simulation results to discuss when you get back!

**Comment by dlevenstein** [comment]
or I guess technically 3 days ago :p

**Comment by dlevenstein** [comment]
oh - the “bug” in the documentation if cell numbers aren’t 1:Ncells isn’t a life-breaking bug… It just takes way lots of memory if your cells are numbered like 90, 100, 500, 700. (because it makes a 700.^i sparse matrix). 

It does throw a warning saying you should change your cell numbers if your highest cell number is much bigger than your number of total cells. 

The alternative was to rename the cells 1:numcells and then spit out a reference map to use with all further analysis..., but I figured it was important to maintain cell number consistency and that was super confusing…

**Comment by dlevenstein** [comment]
also can you throw spikes2sorted in buzcode.  this will be useful to me as I go back and forth between the two formats often, and foolishly just copy the same chunk of code

**Comment by DavidTingley** [comment]
Yea I will, I thought we did away with sparse matrices? Or is this the older version?  Adding  a line that renumbered unit IDs or uses the .UID field from bz_getspikes could fix this

**Comment by dlevenstein** [comment]
EventTree still uses sparse matrices (which is the one I updated)

hash_eventtree doesn’t, which I haven’t used. I think you mentioned that hash is good for large chains >8 but not as good for shorter chains?

**Pull request merged**
